### PR TITLE
fix error when open connection in 'opening' state

### PR DESCRIPTION
**Pull request by marfenij**
rare error when run integration tests from EF Core

### CODE REVIEW

**Comment by marfenij** [comment]
this error not fixed yet

**Comment by jskeet** [comment]
@marfenij: Do you mean that this change doesn't fix the problem?

**Comment by marfenij** [comment]
@benwulfe 
yes, that exception still present in tests:
`SpannerDatabaseCreatorTest.CreateTables_creates_schema_in_existing_database()
SpannerDatabaseCreatorTestHasTables_returns_false_when_database_exists_but_has_no_tables()`

**Comment by marfenij** [comment]
@benwulfe it's a mystery, today all test passed (at home and at office ) I really don't know what is going on...

**Comment by benwulfe** [comment]
@marfenij It should be an error to call Open from multiple threads on a single connection.  I do know that I recently fixed an issue when trying to open a connection prior to a Ddl command.  There was an optimization path that never set the state to open when a connection string was used that did NOT have a database (eg Data Source=/projects/p/instance/i).
Could that have been the issue?
If this happens again for you, please capture the parallel stacks and try to see:
a) the current state of the connection when open is called.
b) any additional threads trying to execute the same connection and call open.

**Comment by benwulfe** [comment]
By the way @marfenij, my fork can be quite out of date (especially master) -- so I suggest you test and do PRs on our main repo.  The main repo is now fully up to date with respect to Entity Framework, so there shouldnt be any reason to use my fork.

**Comment by marfenij** [comment]
Thank you @benwulfe 
I'll try it on main repo

**Pull request closed without merging**
